### ISSUE TITLE
Some question on bos_function

### ISSUE THREAD

**Issue by yangc22** [daizhongxiang/Bayesian-Optimization-Meets-Bayesian-Optimal-Stopping#1]
Hi, in the `bos_function.py` script when computing the termination loss as
```python
loss_d = K2 * Pr_z_star + C * step
loss_d_star = K1 * (1 - Pr_z_star) + C * step
```
why there is the extra `C * step` term which is different than the equation on paper?
Thanks~

**Comment by daizhongxiang** [comment]
Hi,

Thanks for your interest in our paper. This extra term is here because we implemented a slightly different version of the backward induction algorithm from that shown in the paper, but both implementations lead to identical decision rules, as analyzed below.

Firstly, at the last step n=N (which is where our backward induction algorithm begins), the two lines of code amount to adding a constant term (N c_{d_0}) to each of the two termination losses for d_1 and d_2, so the resulting decision rule remains the same.

Next, at the second last step n=N-1, according to the algorithm in the paper, the expected loss can be expressed as (this is simply an expanded version of Eq. (2) in the main paper):
![image](https://user-images.githubusercontent.com/12882841/62370218-390cad80-b564-11e9-9ee8-9c80496087fd.png)

In contrast, according to our implementation, the expected loss should be expressed as (please refer to the two lines of code you attached, and lines 125-137 of the code):
![image](https://user-images.githubusercontent.com/12882841/62370269-4164e880-b564-11e9-9bde-8b212e3a98d0.png)

It can be observed that compared to the first equation, in the second equation, each of the three terms within the min operator is offset by a constant (N-1)c_{d_0}, which doesn't affect the resulting decision rule.

By induction, the same analysis procedure applies for all previous steps for n<N-1, which means the resulting decision rules are exactly the same.

Hope this clarifies.

Best regards,
Zhongxiang

**Comment by yangc22** [comment]
Cool, thank you so much for your awesome explanation!
Another question I have about this awesome work is that the BOS problem is only solved once after some initial training epochs, and the decision does not update as the training goes on afterwards. Why not choose to solve the BOS problem every time after new epoch training?

**Comment by daizhongxiang** [comment]
Hi,

The main practical consideration is the computational cost, since every time we solve the BOS problem, we need to run the backward induction algorithm to get an entire set of decision rules, which will quickly become prohibive if we run this after every epoch. So I think this would only be possible if we can somehow significantly reduce the cost of the backward induction algorithm, e.g., by dramatically reducing the number of forward simulation samples, but this will for sure affect the quality of the decision rules because of reduced approximation quality.
In addition, I believe this will also pose additional challenge in the theoretical analysis.

Thanks.

**Comment by yangc22** [comment]
Hi Zhongxiang,

Thank you so much for your excellent answer. By saying pose additional challenge, do you  mean if reducing the number of forward simulation samples to save the computational cost or computing the BOS problem after every epoch? 
Learned a lot from your awesome work and I really appreciate it!

**Comment by daizhongxiang** [comment]
Hi,

I was referring to if we compute the BOS problem after every epoch, this may pose additional challenge for the theoretical analysis.

Thanks a lot for your interest in our work!

**Comment by yangc22** [comment]
Thank you so much for all the awesome answers Zhongxiang! Hope to see more of your awesome work!
